# Generated by Django 5.2.9 on 2025-12-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bd',
            new_name='Bb',
        ),
    ]
